name: Generate coverage badge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  generate-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov pytest-xdist coverage
      - name: Run tests and produce coverage
        run: |
          pytest --cov=splurge_lazyframe_compare --cov-report=xml -q || true
          # Parse coverage.xml using a small committed script to avoid YAML heredoc
          python tools/generate_coverage_badge.py
      - name: Smoke check coverage
        run: |
          if [ ! -f coverage-percent.txt ]; then
            echo "coverage-percent.txt missing; writing unknown"
            echo unknown > coverage-percent.txt
            exit 0
          fi
          PERCENT=$(cat coverage-percent.txt)
          if ! echo "$PERCENT" | grep -E '^[0-9]+(\.[0-9]+)?$' >/dev/null; then
            echo "coverage-percent.txt malformed or unknown; leaving as unknown"
            exit 0
          fi
          if (( $(echo "$PERCENT <= 0.0" | bc -l) )); then
            echo "coverage percent is zero or negative; skipping badge update"
            exit 0
          fi
      - name: Generate badge and open PR (idempotent)
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x .github/scripts/generate_coverage_badge.sh
          ./.github/scripts/generate_coverage_badge.sh
