name: Test (Python 3.12)

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test-py312:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: |
          pytest --cov=splurge_lazyframe_compare --cov-report=xml -q
